### ISSUE TITLE
BERT & Elmo - Static Vector Transformation Test 2

### ISSUE THREAD

**Issue by CahidArda** [Turkish-Word-Embeddings/Word-Embeddings-Repository-for-Turkish#10]
### The feature, motivation and pitch

We tried to convert contextual embeddings to static vectors using the first method in [this paper](https://arxiv.org/pdf/2106.04302.pdf). We simply produced the embeddings for each word. This didn't work well which is inline with the paper. Paper suggests another option which is to aggregate every sentence which includes the word.

This shall be tested.

**Comment by KarahanS** [comment]
Completed.
