### ISSUE TITLE
Word Embeddings Website

### ISSUE THREAD

**Issue by CahidArda** [Turkish-Word-Embeddings/Word-Embeddings-Repository-for-Turkish#11]
### The feature, motivation and pitch

We want to create a website where users can generate embeddings. @KarahanS suggested using [webvectors](https://github.com/akutuzov/webvectors). Problem with webvectors is that this page loads all of the model into memory and the memory requirement exceeds free plan of AWS.

We can either:
- Pay for AWS
- Use TULAP server
- Instead of webvectors, use a redis database [[1](https://platform.openai.com/docs/guides/embeddings/how-can-i-retrieve-k-nearest-embedding-vectors-quickly), [2](https://github.com/openai/openai-cookbook/blob/main/examples/vector_databases/Using_vector_databases_for_embeddings_search.ipynb), [3](https://github.com/redis/redis-py)] as a vector database. It shouldn't load every word into memory. We can set up redis on free tier EC2 and serve a static page on github pages. **Issue**: Redis is in-memory. It won't fit.
- Pinecone: Web embeddings database on cloud. Free level can fit one of our models [[4](https://docs.pinecone.io/docs/indexes#starter-plan), [5](https://www.pinecone.io/learn/updated-free-plan/)].
- Cold start with Heroku. Couldn't find much about this.

**Comment by KarahanS** [comment]
Deployed on GCP using educational credits provided by Google. We have to make updates on our service such that:
1. Output is returned as an API response to the TULAP interface.
2. Think about how to efficiently use the RAM. (Vector database?)
