### ISSUE TITLE
ACM Paper - `CCSXML` section

### ISSUE THREAD

**Issue by CahidArda** [Turkish-Word-Embeddings/Word-Embeddings-Repository-for-Turkish#13]
### The doc issue

There is a section called `CCSXML` in the paper template:
```latex
%%
%% The code below is generated by the tool at http://dl.acm.org/ccs.cfm.
%% Please copy and paste the code instead of the example below.
%%
\begin{CCSXML}
...
```
It wants us to classify our paper using [an online tool](http://dl.acm.org/ccs.cfm). I don't know how to classify the paper exatly.

### Suggest a potential alternative/fix

I am going to search for `word embeddings` in the [ACM digital library](https://dl.acm.org/action/doSearch?AllField=word+embeddings) and look at the classifications there. I will classify our paper with similar topics.

**Comment by KarahanS** [comment]
I think this issue is completed.
