### ISSUE TITLE
Regarding Reference #14

### ISSUE THREAD

**Issue by gsoykan** [Turkish-Word-Embeddings/Word-Embeddings-Repository-for-Turkish#19]
### The doc issue

> Aylin Üstün, Murat Kurfalı, and Burcu Can. 2018. Characters or morphemes: How to represent words?. In Proceedings of The Third Workshop on Representation Learning for NLP. 144–153.

Author names are incorrect. e.g. It should have been Ahmet Üstün for the first author.

### Suggest a potential alternative/fix

Ahmet Üstün, Murathan Kurfalı, and Burcu Can. 2018. [Characters or Morphemes: How to Represent Words?](https://aclanthology.org/W18-3019). In Proceedings of the Third Workshop on Representation Learning for NLP, pages 144–153, Melbourne, Australia. Association for Computational Linguistics.

**Comment by KarahanS** [comment]
Thank you very much @gsoykan, citation is fixed now.
