### ISSUE TITLE
Wiki Enhancement

### ISSUE THREAD

**Issue by KarahanS** [Turkish-Word-Embeddings/Word-Embeddings-Repository-for-Turkish#2]
### The doc issue

I'm trying to make our wiki page look better and more informative. There are some wiki pages that do not contain any content yet. For the links, please refer to the home wiki page: https://github.com/Turkish-Word-Embeddings/Word-Embeddings-Repository-for-Turkish/wiki/
- [ ] **Prerequisites**: This will be a page about what to install to run the scripts. We already have `requirements.txt` but there are unnecessary libraries for someone who is going to use only a specific algorithm and not the others. That would be nice to list requirements specific to algorithms. 
- [ ] **Training**: Instructions on how to train each model.
- [ ] **Intrinsic and Extrinsic Evaluations**: Instructions on how to run evaluation scripts on models and word vectors.
- [ ] **Documentation of Experimental Results**: Instructions on how to generate tables from experiment results.

**Comment by CahidArda** [comment]
### Requirements Page

Did you use `pip freeze` to get the packages?

### Evaluation and Results Pages

About "Intrinsic and Extrinsic Evaluations" and "Documentation of Experimental Results", are we referring to the [evaluation package](https://github.com/Turkish-Word-Embeddings/Word-Embeddings-Repository-for-Turkish/tree/main/evaluation); if so, can't they be under a single page?

We currently have a README file in the directory explaining how it works. I will improve this README. Should I move the README to a wiki page?

**Comment by KarahanS** [comment]
* Yep, I used `pip freeze` to get the packages. I thought of putting comments to the file in order to specify which library is used for what (like this one: https://github.com/allenai/allennlp/blob/v0.8.3/requirements.txt).
* Great idea. We can combine them into a single page and move the README.

**Comment by KarahanS** [comment]
Note to ourselves: Don't forget to add visual comparison of models (generated with `visualize.py`) to the report before the midterm progress deadline.

**Comment by KarahanS** [comment]
Added [Word2Vec-Training](https://github.com/Turkish-Word-Embeddings/Word-Embeddings-Repository-for-Turkish/wiki/Word2Vec-Training) and [FastText-Training](https://github.com/Turkish-Word-Embeddings/Word-Embeddings-Repository-for-Turkish/wiki/FastText-Training).

**Comment by KarahanS** [comment]
Completed.
