### ISSUE TITLE
Elmo Word Vectors

### ISSUE THREAD

**Issue by KarahanS** [Turkish-Word-Embeddings/Word-Embeddings-Repository-for-Turkish#4]
### The feature, motivation and pitch

As our fourth algorithm, we have to train word vectors using [ELMo](https://allenai.org/allennlp/software/elmo). There are different implementations by the same research institution. 

- [ ] TensorFlow implementation: https://github.com/allenai/bilm-tf - It's not maintained and the TensorFlow version is too old. I tried to run it using `python 3.6` but encountered with some errors running the unittests. This option is on hold for now.
- [ ] Pytorch implementation: https://github.com/allenai/allennlp/blob/main/allennlp/modules/elmo.py - This is the most recent and I believe more stable version. Haven't tried yet, but these are the instructions to train word embeddings: https://github.com/allenai/allennlp/blob/v0.8.3/tutorials/how_to/training_transformer_elmo.md
- [ ] Pytorch implementation wrapper: https://github.com/HIT-SCIR/ELMoForManyLangs

**Note**: We can use [AllenNLP](https://github.com/allenai/allennlp) for both ELMo and BERT. It is not as straightforward as gensim but provides instructions on how to train the models.

**Comment by CahidArda** [comment]
Elmo embeddings were created and added to the report.
