### ISSUE TITLE
BERT Word Vectors

### ISSUE THREAD

**Issue by KarahanS** [Turkish-Word-Embeddings/Word-Embeddings-Repository-for-Turkish#8]
### The feature, motivation and pitch

BERT, Bidirectional Encoder Representations from Transformers, is designed to pretrain deep bidirectional representations from
unlabeled text by jointly conditioning on both left and right context in all layers. As a result, the pre-trained BERT model can be finetuned with just one additional output layer to create state-of-the-art models for a wide range of tasks, such as question answering and language inference, without substantial taskspecific architecture modifications.

There are different sources online for BERT word embeddings. Here are some of them:
* Train BERT from scratch: https://towardsdatascience.com/how-to-train-a-bert-model-from-scratch-72cfce554fc6 (It actually trains a specific case of BERT called roBERTa - there are several different versions of BERT)
* How to fine-tune a BERT model: https://www.tensorflow.org/tfmodels/nlp/fine_tune_bert
* Turkish BERT models repository: https://github.com/stefan-it/turkish-bert

It seems like selecting a proper BERT model from the repository and fine-tuning it using our corpus is the most realistic solution. We can also follow the first tutorial to train our own from scratch.

**Comment by CahidArda** [comment]
BERT embeddings were created and added to the report.
